### ISSUE TITLE
Java 9 Convenience Factory Methods for Collections

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/modernizer-maven-plugin#46]
Evaluate closer to Java 9 release:

http://openjdk.java.net/jeps/269

**Comment by Stephan202** [comment]
Hi @andrewgaul. Just saw fed226a792e3e1f6cd60fcdd846b22fc4a6ec831. We have a code base in which Guava's `Immutable*` types are extensively passed around. In particular, many a field and return type is explicitly immutable. This has merit far beyond the convenience that the static factory methods on these types provide. As such I'm not sure that the violations added in the aforementioned commit make sense, at least as a default; they don't make Guava's variants obsolete or outdated. WDYT?

**Comment by andrewgaul** [comment]
@Stephan202 The `ImmutableMap` vs. `Map` deprecation trick is a neat trick although I have not used it in my projects.  Do you think the exclusion patterns added in #55 allow you sufficient control over these violations in your projects?  I agree that some violations have arguable value although I think modernizer should improve its configuration to allow users to select what they want and add more violations if needed, e.g., #22.

**Comment by Stephan202** [comment]
@andrewgaul Thanks, I tested the #55 feature using version 1.5.0 of the plugin with the exclusion pattern `org/joda/time/.*` (because we're "midway" in our migration from Joda to `java.time`) and this works as expected. My concern about `Immutable*` usage would then call for an exclusion pattern of the form `com/google/common/collect/Immutable\w+\.of:` (or something like that, didn't test it).

As for #22: that looks interesting too. I might have some use cases for that, but will play around with it some other time.
